# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jake Keogh for Knox
description: > # this means to ignore newlines until "baseurl:"
  Jake Keogh for Knox
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jakekeogh.com.au" # the base hostname & protocol for your site

candidate: Jake Keogh
party:
division: Knox
authorisation: >
  Authorised by Jake Keogh 1/8 Democrat Drive, The Basin 3154

collections:
  releases:
    output: true
    permalink: /media/release/:name:output_ext

# Build settings
markdown: kramdown
sass_dir: _sass
