# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jake Keogh for Maroondah
description: > # this means to ignore newlines until "baseurl:"
  Jake Keogh, Labor for Maroondah.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jakekeogh.com.au" # the base hostname & protocol for your site

candidate: Jake Keogh
party:
division: Maroondah
authorisation: >
  Authorised by Jake Keogh, XX Some Road, The Basin

collections:
  releases:
    output: true
    permalink: /media/release/:name:output_ext

# Build settings
markdown: kramdown
